[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
icd = { path = "../icd" }
postcard-rpc = { version = "0.5.0", features = ["use-std", "raw-nusb"] }